# Generated by Django 4.2.13 on 2024-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='students', to='lesson_4.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='task2model2',
            name='task2_model1',
        ),
        migrations.DeleteModel(
            name='Task2Model1',
        ),
        migrations.DeleteModel(
            name='Task2Model2',
        ),
    ]
