# Generated by Django 4.2.13 on 2024-07-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_4', '0006_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Bad')])),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_4.user')),
            ],
        ),
    ]
