# Generated by Django 4.2.13 on 2024-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_7', '0003_remove_customerreview_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
