# Generated by Django 4.2.13 on 2024-07-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_4', '0007_alter_user_phone'),
        ('lesson_7', '0004_alter_customerreview_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lesson_4.product'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lesson_4.user'),
        ),
    ]
