# Generated by Django 4.2.13 on 2024-08-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='notes',
            new_name='memo',
        ),
    ]
